# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to='projects/'),
        ),
    ]
