# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
    ]
